### ISSUE TITLE
Add color support

### ISSUE THREAD

**Issue by rohit-smpx** [pinojs/pino-http-print#3]
Since `pino-pretty` already supports color output using `chalk`, we could add the same to http logs. I can open a PR if this seems like a good idea

**Comment by mcollina** [comment]
Go for it

**Comment by rohit-smpx** [comment]
Should I just import the colorize methods from [`pino-pretty/lib/colors`](https://github.com/pinojs/pino-pretty/blob/master/lib/colors.js)?

**Comment by rohit-smpx** [comment]
> Should I just import the colorize methods from [`pino-pretty/lib/colors`](https://github.com/pinojs/pino-pretty/blob/master/lib/colors.js) [](/pinojs/pino-pretty/blob/HEAD@{2019-11-12T06:06:19Z}/lib/colors.js)?

Decided against it, was only useful for level logging
